version: '3.8'

services:
  postgres:
    build:
      context: ..
      dockerfile: docker/Dockerfile.postgres
    container_name: wiki-postgres
    environment:
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: wiki_password
      POSTGRES_DB: wiki_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: